version: "3"
services:
  tensorflow:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./DeepLearningZeroToAll:/notebooks
    ports:
      - "8888:8888"
    command: python /notebooks/lab-06-1-softmax_classifier.py
